Performance difference between NumPy and python

a NumPy array of one million integers and the equivalent Python list

In [1]:
import numpy as np

In [3]:
my_arr = np.arange(1_000_000)

In [4]:
my_list = list(range(1_000_000))

In [5]:
%timeit myarr2 = my_arr * 2

1.29 ms ± 137 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
%timeit my_list2 = [x * 2 for x in my_list]

76.6 ms ± 18.7 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


%timeit is an IPython magic command it measures how long a piece of code takes to execute

#The NumPy ndarray (A multidimensional Array object)

arrays enables us to perform mathematical operations on whole block of data

In [7]:
import numpy as np
data = np.array([[1.5,-0.1,3],[0,-3,6.5]])

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [ ]:
data

mathematical operation with data

In [8]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [9]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In the first example, all of the elements have been multiplied by 10. In the second, the
corresponding values in each “cell” in the array have been added to each other.

An ndarray is a generic multidimensional container for homogeneous data; that is, all of the elements must be the same type

Every array has a shape, a tuple indicating the size of each dimension and a

dtype, an object describing the data type of the array

In [10]:
data.shape #tuple indicating size of each dimension

(2, 3)

In [11]:
data.dtype #an object describing the data type of array

dtype('float64')